# fly.toml app configuration file generated for courageextractfive on 2023-06-28T23:37:02+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "courageextractfive"
primary_region = "fra"

[build]
  builder = "paketobuildpacks/builder:base"
  env = ["BP_PYTHON_VERSION=3.9.12"]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
