# fly.toml app configuration file generated for couragextractthree on 2023-06-28T23:12:55+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "couragextractthree"
primary_region = "fra"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
