# fly.toml app configuration file generated for courageextractionten on 2023-06-29T00:59:50+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "courageextractionten"
primary_region = "fra"

[build]
  builtin = "python"
  [build.settings]
    pythonbase = "3.9.12-slim"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
