# fly.toml app configuration file generated for courageextracteight on 2023-06-29T00:24:37+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "courageextracteight"
primary_region = "fra"

[build]
  builder = "paketobuildpacks/builder:base"

[[build.buildpacks]]
  id = "paketo-buildpacks/python"
  version = "3.9.10"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[requires]
python_version = "3.9.12"